apiVersion: v1
kind: Secret
metadata:
  name: scheduler-secrets
  namespace: distributed-scheduler
type: Opaque
stringData:
  # PostgreSQL
  postgres-user: "user"
  postgres-password: "password"

  # Redis
  redis-password: "password"

  # NATS (если нужна аутентификация)
  nats-user: "nats"
  nats-password: "password"